clusterName: ""
organization: ""

userConfig:
  certManager:
    configMap:
      values: |
        controller:
          extraArgs:
            # cert-manager's DNS01 solver by default tries to reach authoritative nameservers directly, using
            # their public IPs. Since those are not reachable from private clusters, we instead rely on the
            # recursive nameserver (for AWS, that's normally the default nameserver requested in EC2 instances).
            #
            # Without this, we get an error like
            #
            #   cert-manager/challenges "msg"="propagation check failed" "error"="dial tcp 205.251.194.0:53: i/o timeout"
            #
            # where the IP is an AWS nameserver, and DNS-over-TCP is attempted after UDP has failed before.
            #
            # For public clusters, this setting should have no effect, as they can use the HTTP01 solver.
            - --dns01-recursive-nameservers-only
  externalDns:
    configMap:
      values: |
        aws:
          irsa: "true"
  cilium:
    configMap:
      values: |
        ipam:
          mode: kubernetes
        k8sServiceHost: api.{{ .Values.baseDomain }}
        k8sServicePort: "6443"
        kubeProxyReplacement: strict
        defaultPolicies:
          enabled: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
            - key: CriticalAddonsOnly
              operator: Exists
  netExporter:
    configMap:
      values: |
        NetExporter:
          NTPServers: 169.254.169.123

apps:
  aws-cloud-controller-manager:
    appName: aws-cloud-controller-manager
    chartName: aws-cloud-controller-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/aws-cloud-controller-manager-app
    version: 1.24.1-gs7
  aws-ebs-csi-driver:
    appName: aws-ebs-csi-driver
    chartName: aws-ebs-csi-driver-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/aws-ebs-csi-driver-app
    version: 2.23.0
  aws-pod-identity-webhook:
    appName: aws-pod-identity-webhook
    chartName: aws-pod-identity-webhook
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/aws-pod-identity-webhook
    version: 1.9.0
  capi-node-labeler:
    appName: capi-node-labeler
    chartName: capi-node-labeler
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/capi-node-labeler-app
    version: 0.3.4
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.6.0
  certManager:
    appName: cert-manager
    chartName: cert-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-manager-app
    version: 2.22.0
  coreDNS:
    appName: coredns
    chartName: coredns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/coredns-app
    version: 1.17.0
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.10.0
  externalDns:
    appName: external-dns
    chartName: external-dns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/external-dns-app
    version: 2.37.0
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 2.2.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.16.1
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.16.1
  vpa:
    appName: vertical-pod-autoscaler
    chartName: vertical-pod-autoscaler-app
    catalog: default
    dependsOn: vertical-pod-autoscaler-crd
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-app
    version: 3.4.2
  vpaCRD:
    appName: vertical-pod-autoscaler-crd
    chartName: vertical-pod-autoscaler-crd
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-crd
    version: 2.0.1
  observabilityBundle:
    appName: observability-bundle
    chartName: observability-bundle
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    inCluster: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/observability-bundle
    version: 0.6.0
