clusterName: ""
organization: ""

userConfig:
  certManager:
    configMap:
      values: |
        controller:
          extraArgs:
            # cert-manager's DNS01 solver by default tries to reach authoritative nameservers directly, using
            # their public IPs. Since those are not reachable from private clusters, we instead rely on the
            # recursive nameserver (for AWS, that's normally the default nameserver requested in EC2 instances).
            #
            # Without this, we get an error like
            #
            #   cert-manager/challenges "msg"="propagation check failed" "error"="dial tcp 205.251.194.0:53: i/o timeout"
            #
            # where the IP is an AWS nameserver, and DNS-over-TCP is attempted after UDP has failed before.
            #
            # For public clusters, this setting should have no effect, as they can use the HTTP01 solver.
            - --dns01-recursive-nameservers-only
  externalDns:
    configMap:
      values: |
        aws:
          irsa: "true"
  netExporter:
    configMap:
      values: |
        NetExporter:
          NTPServers: 169.254.169.123
  etcdKubernetesResourceCountExporter:
    configMap:
      values: |
        etcd:
          hostPath: "/etc/kubernetes/pki/etcd/"
          cacertpath: "/certs/ca.crt"
          certpath: "/certs/server.crt"
          keypath: "/certs/server.key"
          prefix: "/registry/"
        events:
          prefix: "/registry/events/"

apps:
  aws-pod-identity-webhook:
    appName: aws-pod-identity-webhook
    chartName: aws-pod-identity-webhook
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/aws-pod-identity-webhook
    version: 1.9.1
  capi-node-labeler:
    appName: capi-node-labeler
    chartName: capi-node-labeler
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/capi-node-labeler-app
    version: 0.3.4
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.6.0
  certManager:
    appName: cert-manager
    chartName: cert-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-manager-app
    version: 2.24.1
  externalDns:
    appName: external-dns
    chartName: external-dns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/external-dns-app
    version: 2.37.1
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 2.2.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.16.2
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.16.1
  vpa:
    appName: vertical-pod-autoscaler
    chartName: vertical-pod-autoscaler-app
    catalog: default
    dependsOn: prometheus-operator-crd
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-app
    version: 3.5.3
  observabilityBundle:
    appName: observability-bundle
    chartName: observability-bundle
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    inCluster: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/observability-bundle
    version: 0.7.1
  etcdKubernetesResourceCountExporter:
    appName: etcd-kubernetes-resources-count-exporter
    chartName: etcd-kubernetes-resources-count-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/etcd-kubernetes-resources-count-exporter
    version: 1.3.0
