clusterName: ""
organization: ""
aws:
  iam:
    customRoleName: ""

userConfig:
  externalDns:
    configMap:
      values: |
        serviceAccount:
          create: false
          name: "external-dns"
        aws:
          iam:
            customRoleName: "{{ .Values.aws.iam.customRoleName }}"
          irsa: "true"
  cilium:
    configMap:
      values: |
        ipam:
          mode: kubernetes
        k8sServiceHost: api.{{ .Values.baseDomain }}
        k8sServicePort: 6443
        kubeProxyReplacement: strict
        hubble:
          relay:
            enabled: true
        defaultPolicies:
          enabled: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
            - key: CriticalAddonsOnly
              operator: Exists

apps:
  aws-ebs-csi-driver:
    appName: aws-ebs-csi-driver
    chartName: aws-ebs-csi-driver-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/aws-ebs-csi-driver-app
    version: 2.19.0
  aws-pod-identity-webhook:
    appName: aws-pod-identity-webhook
    chartName: aws-pod-identity-webhook
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/aws-pod-identity-webhook
    version: 1.1.1
  capi-node-labeler:
    appName: capi-node-labeler
    chartName: capi-node-labeler
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/capi-node-labeler-app
    version: 0.3.4
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.3.0
  certManager:
    appName: cert-manager
    chartName: cert-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-manager-app
    version: 2.18.0
  coreDNS:
    appName: coredns
    chartName: coredns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/coredns-app
    version: 1.11.0
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.6.1
  externalDns:
    appName: external-dns
    chartName: external-dns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/external-dns-app
    version: 2.19.0
  kiam:
    appName: kiam
    chartName: kiam-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/kiam-app
    version: 2.6.0
  kubeStateMetrics:
    appName: kube-state-metrics
    chartName: kube-state-metrics
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/kube-state-metrics-app
    version: 1.14.1
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 2.0.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.12.0
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.13.0
  vpa:
    appName: vertical-pod-autoscaler
    chartName: vertical-pod-autoscaler-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-app
    version: 2.5.2
  vpaCRD:
    appName: vertical-pod-autoscaler-crd
    chartName: vertical-pod-autoscaler-crd
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-crd
    version: 1.0.1
  observabilityBundle:
    appName: observability-bundle
    chartName: observability-bundle
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    inCluster: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/observability-bundle
    version: 0.1.4
