version: 2.1

orbs:
  architect: giantswarm/architect@5.1.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-cluster-catalog
          context: architect
          executor: app-build-suite
          chart: default-apps-aws
          app_catalog: cluster-catalog
          app_catalog_test: cluster-test-catalog
          filters:
            tags:
              only: /^v.*/
