{{- range $key, $value := .Values.apps }}
{{- $appName := .appName }}
# We want to exclude apps marked for private clusters only from clusters that
# aren't private. At the same time we want to deploy all apps that aren't
# marked with `privateCluster: true` to all clusters, regardless if they are
# private or not.
# This statement will always evaluate to true for non privateCluster apps (true
# or $.Values.cluster.private) and will only evaluate to true when the app is
# marked for private clusters if the cluster is private (false or
# $.Values.cluster.private)
{{- if or (not .privateCluster) $.Values.cluster.private }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "{{ .forceUpgrade }}"
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterName }}-{{ $appName }}
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: {{ .catalog }}
  name: {{ .chartName }}
  namespace: {{ .namespace }}
  version: {{ .version }}
  kubeConfig:
    context:
      name: {{ $.Values.clusterName }}-admin@{{ $.Values.clusterName }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterName }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  {{- with .clusterValues }}
  {{- if or .configMap .secret }}
  config:
  {{- if .configMap }}
    configMap:
      name: {{ $.Values.clusterName }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  {{- end }}
  {{- if .secret }}
    secret:
      name: {{ $.Values.clusterName }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  {{- end }}
  {{- end }} 
{{- end }}
{{- with (get $.Values.userConfig $key) }}
  userConfig:
  {{- if .configMap }}
    configMap:
      name: {{ $.Values.clusterName }}-{{ $appName }}-user-values
      namespace: {{ $.Release.Namespace }}
  {{- end }}
  {{- if .secret }}
    secret:
      name: {{ $.Values.clusterName }}-{{ $appName }}-user-values
      namespace: {{ $.Release.Namespace }}
  {{- end }}
  {{- end }}

{{- with (get $.Values.userConfig $key) }}
{{- if .configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterName }}-{{ $appName }}-user-values
  namespace: {{ $.Release.Namespace }}
data:
  {{- (tpl (.configMap | toYaml | toString) $) | nindent 2 }}
{{- end }}
{{- if .secret }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterName }}-{{ $appName }}-user-values
  namespace: {{ $.Release.Namespace }}
stringData:
  {{- (tpl (.secret | toYaml | toString) $) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
