apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "false"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.clusterName }}-capi-node-labeler
  namespace: {{ .Release.Namespace }}
spec:
  catalog: default
  {{- include "kubeconfig" . | nindent 2 }}
  {{- include "config" . | nindent 2 }}
  name: capi-node-labeler
  namespace: kube-system
  version: 0.3.3
