apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-apps-wait-for-cni
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-apps-wait-for-cni
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-apps-wait-for-cni
subjects:
  - kind: ServiceAccount
    name: default-apps-wait-for-cni
    namespace: {{ .Release.Namespace }}
